import type { ExecutiveIntelligenceReport } from "@/types/intelligence";

/** Fully populated report used by dev-only email and report previews. */
export const SAMPLE_REPORT: ExecutiveIntelligenceReport = {
  id: "preview-report",
  monitorRequirement: "Track Acme pricing, packaging and enterprise positioning",
  verdict: "Acme moved enterprise pricing behind a sales call and launched a usage-based tier",
  situation:
    "Acme replaced its public enterprise price with a 'contact sales' flow and introduced a usage-based tier at $0.004 per request. The pricing page was rewritten within the last 24 hours and the changelog confirms the rollout.",
  impact:
    "Deals in late stage that were benchmarked against Acme's published $2,400/mo enterprise plan now lack a public anchor. Expect procurement to ask for a like-for-like comparison within the week.",
  riskScore: 78,
  confidence: 84,
  hallucinationRisk: "low",
  provider: "bright-data",
  generatedAt: new Date().toISOString(),
  observedFacts: [
    "Enterprise tier price removed from the public pricing page",
    "New usage-based tier listed at $0.004 per request",
    "Changelog entry published 18 hours ago",
  ],
  detectedChanges: [
    {
      id: "c1",
      field: "Acme enterprise plan price",
      oldValue: "$2,400/mo",
      newValue: "Contact sales",
      category: "pricing",
      severity: "critical",
      impact: "Removes the public anchor used in competitive deals",
      sourceUrl: "https://acme.example.com/pricing",
      detectedAt: new Date().toISOString(),
    },
    {
      id: "c2",
      field: "Acme usage tier",
      oldValue: "—",
      newValue: "$0.004 / request",
      category: "pricing",
      severity: "high",
      impact: "Opens a cheaper self-serve entry point below our starter plan",
      sourceUrl: "https://acme.example.com/pricing",
      detectedAt: new Date().toISOString(),
    },
    {
      id: "c3",
      field: "Acme homepage headline",
      oldValue: "Automation for teams",
      newValue: "The enterprise automation platform",
      category: "competitor",
      severity: "medium",
      impact: "Signals an upmarket positioning shift",
      sourceUrl: "https://acme.example.com",
      detectedAt: new Date().toISOString(),
    },
    {
      id: "c4",
      field: "Acme docs navigation",
      oldValue: "Guides",
      newValue: "Guides, Enterprise",
      category: "market",
      severity: "low",
      impact: "Supporting evidence for the enterprise push",
      sourceUrl: "https://docs.acme.example.com",
      detectedAt: new Date().toISOString(),
    },
  ],
  verifiedClaims: [
    {
      id: "v1",
      claim: "Enterprise pricing is no longer published",
      status: "evidence-backed",
      confidence: 93,
      sourceIds: ["s1"],
      sourceRecords: [],
    },
    {
      id: "v2",
      claim: "Usage-based tier targets mid-market self-serve",
      status: "partial",
      confidence: 61,
      sourceIds: ["s2"],
      sourceRecords: [],
    },
    {
      id: "v3",
      claim: "Change is a response to our launch",
      status: "unsupported",
      confidence: 28,
      sourceIds: [],
      sourceRecords: [],
    },
  ],
  actionPlan: [
    "Refresh the competitive battlecard with the new usage-based tier before Thursday's pipeline review",
    "Brief AEs on the 'contact sales' change and give them a public-price talk track",
    "Model our effective per-request cost against $0.004 for the top 10 open deals",
  ],
  watchItems: [
    "Acme pricing page",
    "Acme changelog",
    "Acme enterprise landing page",
  ],
  forecasts: ["Public enterprise pricing is unlikely to return this quarter"],
  evidenceSources: [
    {
      id: "s1",
      title: "Acme pricing",
      publisher: "acme.example.com",
      url: "https://acme.example.com/pricing",
      freshness: "18 hours ago",
      reliability: 94,
      claimSupported: "Enterprise pricing is no longer published",
    },
    {
      id: "s2",
      title: "Acme changelog — usage-based billing",
      publisher: "changelog",
      url: "https://acme.example.com/changelog",
      freshness: "1 day ago",
      reliability: 81,
      claimSupported: "Usage-based tier launched",
    },
    {
      id: "s3",
      title: "Coverage of Acme pricing shift",
      publisher: "TechPress",
      url: "https://techpress.example.com/acme-pricing",
      freshness: "2 days ago",
      reliability: 62,
      claimSupported: "Third-party confirmation of the pricing change",
    },
  ],
};
